### ISSUE TITLE
Clients do not reconnect after server restarts causing crypt issues

### ISSUE THREAD

**Issue by loverend** [napalm-automation/napalm-logs#63]
If the server restarts after the client has connected, then the client is left with old crypto info:

```
Traceback (most recent call last):
  File "/home/luke/git/napalm-logs/test-listen.py", line 19, in <module>
    decrypted = napalm_logs.utils.decrypt(data, vk, pk)
  File "/home/luke/git/napalm-logs/napalm_logs/utils/__init__.py", line 77, in decrypt
    raise BadSignatureException('Signature was forged or corrupt')
napalm_logs.exceptions.BadSignatureException: Signature was forged or corrupt
```

Therefore we need to have the clients restart, or allow them to use the old crypo info (not ideal)

**Comment by mirceaulinic** [comment]
I think this can be tackled together with https://github.com/napalm-automation/napalm-logs/issues/47, as the right way to notify the clients (and implicitly to be aware of what clients are connected and receiving messages) is to maintain the auth socket open. Currently that socket is closed immediately after exchanging the private and signing key exchange.

**Comment by loverend** [comment]
Added auth keep alive in #87, however clients will still fail to decrypt the message and hit an exception if the restarted server sends a new message before the keepalive is sent.

**Comment by mirceaulinic** [comment]
Probably the solution would be to send a notification to the clients before the auth process is stopped.
If the auth process dies without proper shutdown, the clients should try to reconnect, the timeout interval being a random value in ms, increasing after every failed connect attempt.

**Comment by bigpick** [comment]
I think I might be seeing the same behavior currently.

Running the posted authenticated client from https://napalm-logs.readthedocs.io/en/latest/authentication/index.html and versions:
```
napalm-logs 0.6.0
salt 2018.3.2 (Oxygen)
```
When using the test python listener client with the address set to `127.0.0.1`, it quits out with the same error.

Napalm-logs configuration file:
```
certificate: /var/cache/napalm-logs.crt
keyfile: /var/cache/napalm-logs.key
log_file: cli
log_level: debug
address: 172.16.0.1
port: 5514
auth_address: 127.0.0.1
auth_port: 49018
publisher:
  zmq:
    address: 127.0.0.1
    port: 49017
    disable_security: true
```

Python client:
```
gpickering@gctest2-00:~$ python test.py 
No handlers could be found for logger "napalm_logs.utils"
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    decrypted = auth.decrypt(raw_object)  # check the siganture, decrypt and deserialize
  File "/usr/local/lib/python2.7/dist-packages/napalm_logs/utils/__init__.py", line 162, in decrypt
    raise BadSignatureException('Signature was forged or corrupt')
napalm_logs.exceptions.BadSignatureException: Signature was forged or corrupt
```

Napalm-logs log:
```
...
2018-10-12 13:55:32,488,488 [napalm_logs.auth ][INFO    ] ('127.0.0.1', 52224) connected
2018-10-12 13:55:32,488,489 [napalm_logs.auth ][DEBUG   ] Starting the handshake
2018-10-12 13:55:32,489,489 [napalm_logs.auth ][DEBUG   ] Received message INIT from ('127.0.0.1', 52224)
2018-10-12 13:55:32,489,489 [napalm_logs.auth ][DEBUG   ] Sending the private key
2018-10-12 13:55:32,489,489 [napalm_logs.auth ][DEBUG   ] Waiting for the client to confirm
2018-10-12 13:55:32,489,490 [napalm_logs.auth ][DEBUG   ] Sending the signature key
2018-10-12 13:55:32,489,490 [napalm_logs.auth ][DEBUG   ] Waiting for the client to confirm
2018-10-12 13:55:32,489,490 [napalm_logs.auth ][INFO    ] ('127.0.0.1', 52224) is now authenticated
...
2018-10-12 13:55:52,046,047 [napalm_logs.auth ][ERROR   ] Received something other than KEEPALIVE
```
